### ISSUE TITLE
Can't find plugin after install

### ISSUE THREAD

**Issue by ghost** [jweite/logstash-input-csvfile#1]
After installing plugin I use the filter like so:

```
filter {
    csvfile {
        first_line_defines_columns => true
    }
}
```

Logstash complains "no such file to load."
Using Logstash 1.5.4

**Comment by jweite** [comment]
Alex, the csvfile plugin I wrote is an input plugin, not a filter like the one bundled with Logstash. You'll need to declare it in an input section.  

It is derived from the standard file plugin bundled with logstash, so you'll provide it the usual file input plugin attributes, most notably _path_.  I've used:

```
input {
   csvfile {
      path => "c:/temp/csvtest*.log"
      start_position => beginning
      sincedb_path => "c:/logstash-1.5.0/sincedbs/csvfiletest"
      first_line_defines_columns => true
   }
}

output {
   stdout { 
      codec => rubydebug 
   }
}
```

**Comment by rwlaschin** [comment]
I'm having an issue as well.  I pulled down from zip.  And I get an error with this line in the gemspec
s.files = `git ls-files`.split($)

I also needed to adjust the s.add_runtime_dependency line so I went and modified the line to the following:
  s.files = `find . -type f`.split($)  

I'm on linux and this won't work on windows.

**Comment by jweite** [comment]
Thanks for this feedback.  Is the problematic line exactly as typed in your message above?   If so, then backticks surrounding `git ls-files` may have evaporated.

So I'm clear, did `find . -type f.split($)` work for you on Linux?   What logstash version / ruby version are you using?

For background, I derived that gemspec from the one in logstash-input-file, v 1.0.1, which uses the same `git` technique.  Perhaps that wasn't sufficiently portable, as I'm seeing the new versions of logstash-input-file use something like `Dir['lib/**/*','spec/**/*' ... ]`  I'll look into this when I get your further feedback.

**Comment by jweite** [comment]
I went ahead and revised the gemspec with the standard Ruby style (ie non-backtick-git) code for defining s.files.   I also revised dependency versions after rspec testing against logstash-input-file 2.2.1 (and its modern dependents).  This plugin is now published on rubygems.org and was functionally tested against current Logstash 2.1.2 on Windows and Linux (Centos).   Installs in the usual manner with bin/plugin.

**Comment by rwlaschin** [comment]
Thanks.  Looks like you are faster than I.  Yes there are back-ticks -- must have been absorbed in the post.  I pulled master on Feb 8, 2016

Yes the find did work for me.  It may not work for everyone else.

Thanks for your help!

**Comment by jweite** [comment]
Thanks R.  The `Dir['lib/**/*','spec/**/*']` that I ultimately went with should be portable.

Let me know how the plugin works for your application.

**Comment by alex-nishikawa2013** [comment]
We can close this issue
